quarkus.http.host=127.0.0.1

quarkus.log.level=INFO
quarkus.log.category."org.example".level=DEBUG
quarkus.log.category."io.quarkus".level=INFO

quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=combined
quarkus.http.access-log.log-to-file=false

app.max-users-per-page=100
app.default-user-name=Guest

quarkus.datasource.active=false
quarkus.hibernate-orm.active=false
quarkus.hibernate-orm.validation.enabled=false

quarkus.flyway.migrate-at-start=false
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=1
quarkus.flyway.clean-disabled=false

%dev.quarkus.datasource.active=true
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=postgres
%dev.quarkus.hibernate-orm.active=true
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.flyway.migrate-at-start=true

%test.quarkus.datasource.active=true
%test.quarkus.datasource.db-kind=postgresql
%test.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
%test.quarkus.datasource.username=postgres
%test.quarkus.datasource.password=postgres
%test.quarkus.hibernate-orm.active=true
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.flyway.migrate-at-start=true

%prod.quarkus.datasource.active=true
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://127.0.0.1:5432/postgres
%prod.quarkus.datasource.username=postgres
%prod.quarkus.datasource.password=postgres
%prod.quarkus.hibernate-orm.active=true
%prod.quarkus.hibernate-orm.database.generation=none
%prod.quarkus.hibernate-orm.schema-management.strategy=none
%prod.quarkus.flyway.migrate-at-start=false

quarkus.native.auto-service-loader-registration=true
quarkus.native.debug.enabled=false